const express = require('express')
const app = express()
const router = express.Router()
const moment = require('moment-timezone')
moment.tz.setDefault("Europe/Paris")
const appController = require("../controllers/appController")
const authController = require("../controllers/authController")
const betController = require("../controllers/betController")
const competitionController = require("../controllers/competitionController")
const matchController = require("../controllers/matchController")
const playerController = require("../controllers/playerController")
const rewardController = require("../controllers/rewardController")
const seasonController = require("../controllers/seasonController")
const teamController = require("../controllers/teamController")
const userController = require("../controllers/userController")

app.use(appController)
app.use(authController)
app.use(betController)
app.use(competitionController)
app.use(matchController)
app.use(playerController)
app.use(rewardController)
app.use(seasonController)
app.use(teamController)
app.use(userController)

module.exports = router;